kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-hdd
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  storageaccounttype: Standard_LRS
